// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bans.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :one
INSERT INTO banned_users (user_id, reason, banned_by, created_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    reason = EXCLUDED.reason,
    banned_by = EXCLUDED.banned_by,
    created_at = NOW()
RETURNING user_id, reason, banned_by, created_at
`

type BanUserParams struct {
	UserID   int64
	Reason   string
	BannedBy int64
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) (BannedUsers, error) {
	row := q.db.QueryRow(ctx, banUser, arg.UserID, arg.Reason, arg.BannedBy)
	var i BannedUsers
	err := row.Scan(
		&i.UserID,
		&i.Reason,
		&i.BannedBy,
		&i.CreatedAt,
	)
	return i, err
}

const countBannedChatsByType = `-- name: CountBannedChatsByType :one
SELECT COUNT(*)::BIGINT
FROM banned_users b
JOIN chat c ON c.chat_id = b.user_id
WHERE c.type = $1
`

func (q *Queries) CountBannedChatsByType(ctx context.Context, type_ ChatType) (int64, error) {
	row := q.db.QueryRow(ctx, countBannedChatsByType, type_)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countBannedUsers = `-- name: CountBannedUsers :one
SELECT COUNT(*)::BIGINT
FROM banned_users
`

func (q *Queries) CountBannedUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBannedUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const isUserBanned = `-- name: IsUserBanned :one
SELECT EXISTS (
    SELECT 1
    FROM banned_users
    WHERE user_id = $1
)::BOOLEAN
`

func (q *Queries) IsUserBanned(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBanned, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listBannedChatsByType = `-- name: ListBannedChatsByType :many
SELECT
    b.user_id,
    b.reason,
    b.banned_by,
    b.created_at,
    c.title,
    c.username,
    c.first_name,
    c.last_name
FROM banned_users b
JOIN chat c ON c.chat_id = b.user_id
WHERE c.type = $1
ORDER BY b.created_at DESC
LIMIT $2
`

type ListBannedChatsByTypeParams struct {
	Type       ChatType
	LimitCount int32
}

type ListBannedChatsByTypeRow struct {
	UserID    int64
	Reason    string
	BannedBy  int64
	CreatedAt pgtype.Timestamptz
	Title     string
	Username  string
	FirstName string
	LastName  string
}

func (q *Queries) ListBannedChatsByType(ctx context.Context, arg ListBannedChatsByTypeParams) ([]ListBannedChatsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listBannedChatsByType, arg.Type, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBannedChatsByTypeRow
	for rows.Next() {
		var i ListBannedChatsByTypeRow
		if err := rows.Scan(
			&i.UserID,
			&i.Reason,
			&i.BannedBy,
			&i.CreatedAt,
			&i.Title,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBannedUsers = `-- name: ListBannedUsers :many
SELECT
    b.user_id,
    b.reason,
    b.banned_by,
    b.created_at,
    c.username,
    c.first_name,
    c.last_name
FROM banned_users b
JOIN chat c ON c.chat_id = b.user_id AND c.type = 'private'
ORDER BY b.created_at DESC
LIMIT $1
`

type ListBannedUsersRow struct {
	UserID    int64
	Reason    string
	BannedBy  int64
	CreatedAt pgtype.Timestamptz
	Username  string
	FirstName string
	LastName  string
}

func (q *Queries) ListBannedUsers(ctx context.Context, limitCount int32) ([]ListBannedUsersRow, error) {
	rows, err := q.db.Query(ctx, listBannedUsers, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBannedUsersRow
	for rows.Next() {
		var i ListBannedUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Reason,
			&i.BannedBy,
			&i.CreatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanUser = `-- name: UnbanUser :exec
DELETE FROM banned_users
WHERE user_id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, unbanUser, userID)
	return err
}
