// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatByID = `-- name: GetChatByID :one
SELECT
    c.chat_id,
    c.type,
    c.title,
    c.username,
    c.first_name,
    c.last_name,
    s.language,
    c.created_at,
    c.last_seen_at
FROM chat c
JOIN settings s USING (chat_id)
WHERE c.chat_id = $1
LIMIT 1
`

type GetChatByIDRow struct {
	ChatID     int64
	Type       ChatType
	Title      string
	Username   string
	FirstName  string
	LastName   string
	Language   string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

func (q *Queries) GetChatByID(ctx context.Context, chatID int64) (GetChatByIDRow, error) {
	row := q.db.QueryRow(ctx, getChatByID, chatID)
	var i GetChatByIDRow
	err := row.Scan(
		&i.ChatID,
		&i.Type,
		&i.Title,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Language,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getOrCreateChat = `-- name: GetOrCreateChat :one
WITH upsert_chat AS (
    INSERT INTO chat (chat_id, type, title, username, first_name, last_name, last_seen_at)
    VALUES ($1, $2, $3, $4, $5, $6, NOW())
    ON CONFLICT (chat_id) DO UPDATE SET
        type = EXCLUDED.type,
        title = EXCLUDED.title,
        username = EXCLUDED.username,
        first_name = EXCLUDED.first_name,
        last_name = EXCLUDED.last_name,
        last_seen_at = NOW(),
        updated_at = NOW()
    RETURNING chat_id, type, created_at, updated_at, title, username, first_name, last_name, last_seen_at
),
upsert_settings AS (
    INSERT INTO settings (chat_id, language, captions, silent, nsfw, media_album_limit, delete_links)
    VALUES ($1, $7, $8, $9, $10, $11, $12)
    ON CONFLICT (chat_id) DO UPDATE SET
        language = CASE 
            WHEN settings.language = 'XX' THEN EXCLUDED.language 
            ELSE settings.language 
        END
    RETURNING chat_id, nsfw, media_album_limit, captions, silent, language, created_at, updated_at, disabled_extractors, delete_links
),
final_chat AS (
    SELECT chat_id, type, created_at, updated_at, title, username, first_name, last_name, last_seen_at FROM upsert_chat
    UNION ALL
    SELECT chat_id, type, created_at, updated_at, title, username, first_name, last_name, last_seen_at FROM chat WHERE chat_id = $1 AND NOT EXISTS (SELECT 1 FROM upsert_chat)
),
final_settings AS (
    SELECT chat_id, nsfw, media_album_limit, captions, silent, language, created_at, updated_at, disabled_extractors, delete_links FROM upsert_settings
)
SELECT 
    c.chat_id,
    c.type,
    c.title,
    c.username,
    c.first_name,
    c.last_name,
    c.last_seen_at,
    s.nsfw,
    s.media_album_limit,
    s.captions,
    s.silent,
    s.language,
    s.disabled_extractors,
    s.delete_links
FROM final_chat c 
JOIN final_settings s ON s.chat_id = c.chat_id
`

type GetOrCreateChatParams struct {
	ChatID          int64
	Type            ChatType
	Title           string
	Username        string
	FirstName       string
	LastName        string
	Language        string
	Captions        bool
	Silent          bool
	Nsfw            bool
	MediaAlbumLimit int32
	DeleteLinks     bool
}

type GetOrCreateChatRow struct {
	ChatID             int64
	Type               ChatType
	Title              string
	Username           string
	FirstName          string
	LastName           string
	LastSeenAt         pgtype.Timestamptz
	Nsfw               bool
	MediaAlbumLimit    int32
	Captions           bool
	Silent             bool
	Language           string
	DisabledExtractors []string
	DeleteLinks        bool
}

func (q *Queries) GetOrCreateChat(ctx context.Context, arg GetOrCreateChatParams) (GetOrCreateChatRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateChat,
		arg.ChatID,
		arg.Type,
		arg.Title,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Language,
		arg.Captions,
		arg.Silent,
		arg.Nsfw,
		arg.MediaAlbumLimit,
		arg.DeleteLinks,
	)
	var i GetOrCreateChatRow
	err := row.Scan(
		&i.ChatID,
		&i.Type,
		&i.Title,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.LastSeenAt,
		&i.Nsfw,
		&i.MediaAlbumLimit,
		&i.Captions,
		&i.Silent,
		&i.Language,
		&i.DisabledExtractors,
		&i.DeleteLinks,
	)
	return i, err
}

const getPrivateChatByUsername = `-- name: GetPrivateChatByUsername :one
SELECT
    c.chat_id,
    c.type,
    c.title,
    c.username,
    c.first_name,
    c.last_name,
    s.language,
    c.created_at,
    c.last_seen_at
FROM chat c
JOIN settings s USING (chat_id)
WHERE c.type = 'private'
  AND LOWER(c.username) = LOWER($1)
LIMIT 1
`

type GetPrivateChatByUsernameRow struct {
	ChatID     int64
	Type       ChatType
	Title      string
	Username   string
	FirstName  string
	LastName   string
	Language   string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

func (q *Queries) GetPrivateChatByUsername(ctx context.Context, username string) (GetPrivateChatByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getPrivateChatByUsername, username)
	var i GetPrivateChatByUsernameRow
	err := row.Scan(
		&i.ChatID,
		&i.Type,
		&i.Title,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Language,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
