// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDownloadEvent = `-- name: CreateDownloadEvent :exec
INSERT INTO download_events (
    chat_id,
    user_id,
    chat_type,
    extractor_id,
    content_id,
    content_url,
    item_count,
    total_file_size,
    from_cache
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateDownloadEventParams struct {
	ChatID        int64
	UserID        int64
	ChatType      ChatType
	ExtractorID   string
	ContentID     string
	ContentUrl    string
	ItemCount     int32
	TotalFileSize int64
	FromCache     bool
}

func (q *Queries) CreateDownloadEvent(ctx context.Context, arg CreateDownloadEventParams) error {
	_, err := q.db.Exec(ctx, createDownloadEvent,
		arg.ChatID,
		arg.UserID,
		arg.ChatType,
		arg.ExtractorID,
		arg.ContentID,
		arg.ContentUrl,
		arg.ItemCount,
		arg.TotalFileSize,
		arg.FromCache,
	)
	return err
}

const getChatDownloadSummary = `-- name: GetChatDownloadSummary :one
SELECT
    COUNT(*)::BIGINT AS downloads,
    COALESCE(SUM(item_count), 0)::BIGINT AS items,
    COALESCE(SUM(total_file_size), 0)::BIGINT AS total_size,
    MAX(created_at)::TIMESTAMP WITH TIME ZONE AS last_download_at
FROM download_events
WHERE chat_id = $1
`

type GetChatDownloadSummaryRow struct {
	Downloads      int64
	Items          int64
	TotalSize      int64
	LastDownloadAt pgtype.Timestamptz
}

func (q *Queries) GetChatDownloadSummary(ctx context.Context, chatID int64) (GetChatDownloadSummaryRow, error) {
	row := q.db.QueryRow(ctx, getChatDownloadSummary, chatID)
	var i GetChatDownloadSummaryRow
	err := row.Scan(
		&i.Downloads,
		&i.Items,
		&i.TotalSize,
		&i.LastDownloadAt,
	)
	return i, err
}

const getUserDownloadSummary = `-- name: GetUserDownloadSummary :one
SELECT
    COUNT(*)::BIGINT AS downloads,
    COALESCE(SUM(item_count), 0)::BIGINT AS items,
    COALESCE(SUM(total_file_size), 0)::BIGINT AS total_size,
    MAX(created_at)::TIMESTAMP WITH TIME ZONE AS last_download_at
FROM download_events
WHERE user_id = $1
`

type GetUserDownloadSummaryRow struct {
	Downloads      int64
	Items          int64
	TotalSize      int64
	LastDownloadAt pgtype.Timestamptz
}

func (q *Queries) GetUserDownloadSummary(ctx context.Context, userID int64) (GetUserDownloadSummaryRow, error) {
	row := q.db.QueryRow(ctx, getUserDownloadSummary, userID)
	var i GetUserDownloadSummaryRow
	err := row.Scan(
		&i.Downloads,
		&i.Items,
		&i.TotalSize,
		&i.LastDownloadAt,
	)
	return i, err
}

const listChatPlatformStats = `-- name: ListChatPlatformStats :many
SELECT
    extractor_id,
    COUNT(*)::BIGINT AS downloads,
    COALESCE(SUM(total_file_size), 0)::BIGINT AS total_size
FROM download_events
WHERE chat_id = $1
GROUP BY extractor_id
ORDER BY downloads DESC, total_size DESC
LIMIT $2
`

type ListChatPlatformStatsParams struct {
	ChatID     int64
	LimitCount int32
}

type ListChatPlatformStatsRow struct {
	ExtractorID string
	Downloads   int64
	TotalSize   int64
}

func (q *Queries) ListChatPlatformStats(ctx context.Context, arg ListChatPlatformStatsParams) ([]ListChatPlatformStatsRow, error) {
	rows, err := q.db.Query(ctx, listChatPlatformStats, arg.ChatID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatPlatformStatsRow
	for rows.Next() {
		var i ListChatPlatformStatsRow
		if err := rows.Scan(&i.ExtractorID, &i.Downloads, &i.TotalSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatRecentDownloadEvents = `-- name: ListChatRecentDownloadEvents :many
SELECT
    de.extractor_id,
    de.content_id,
    de.content_url,
    de.user_id,
    COALESCE(NULLIF(de.user_username, ''), uc.username, '') AS user_username,
    COALESCE(NULLIF(de.user_first_name, ''), uc.first_name, '') AS user_first_name,
    COALESCE(NULLIF(de.user_last_name, ''), uc.last_name, '') AS user_last_name,
    de.item_count,
    de.total_file_size,
    de.from_cache,
    de.created_at
FROM download_events de
LEFT JOIN chat uc ON uc.chat_id = de.user_id
WHERE de.chat_id = $1
ORDER BY de.created_at DESC
LIMIT $2
`

type ListChatRecentDownloadEventsParams struct {
	ChatID     int64
	LimitCount int32
}

type ListChatRecentDownloadEventsRow struct {
	ExtractorID   string
	ContentID     string
	ContentUrl    string
	UserID        int64
	UserUsername  string
	UserFirstName string
	UserLastName  string
	ItemCount     int32
	TotalFileSize int64
	FromCache     bool
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListChatRecentDownloadEvents(ctx context.Context, arg ListChatRecentDownloadEventsParams) ([]ListChatRecentDownloadEventsRow, error) {
	rows, err := q.db.Query(ctx, listChatRecentDownloadEvents, arg.ChatID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatRecentDownloadEventsRow
	for rows.Next() {
		var i ListChatRecentDownloadEventsRow
		if err := rows.Scan(
			&i.ExtractorID,
			&i.ContentID,
			&i.ContentUrl,
			&i.UserID,
			&i.UserUsername,
			&i.UserFirstName,
			&i.UserLastName,
			&i.ItemCount,
			&i.TotalFileSize,
			&i.FromCache,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlatformStats = `-- name: ListUserPlatformStats :many
SELECT
    extractor_id,
    COUNT(*)::BIGINT AS downloads,
    COALESCE(SUM(total_file_size), 0)::BIGINT AS total_size
FROM download_events
WHERE user_id = $1
GROUP BY extractor_id
ORDER BY downloads DESC, total_size DESC
LIMIT $2
`

type ListUserPlatformStatsParams struct {
	UserID     int64
	LimitCount int32
}

type ListUserPlatformStatsRow struct {
	ExtractorID string
	Downloads   int64
	TotalSize   int64
}

func (q *Queries) ListUserPlatformStats(ctx context.Context, arg ListUserPlatformStatsParams) ([]ListUserPlatformStatsRow, error) {
	rows, err := q.db.Query(ctx, listUserPlatformStats, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPlatformStatsRow
	for rows.Next() {
		var i ListUserPlatformStatsRow
		if err := rows.Scan(&i.ExtractorID, &i.Downloads, &i.TotalSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRecentDownloadEvents = `-- name: ListUserRecentDownloadEvents :many
SELECT
    de.extractor_id,
    de.content_id,
    de.content_url,
    de.chat_id,
    de.chat_type,
    c.title AS chat_title,
    c.username AS chat_username,
    de.item_count,
    de.total_file_size,
    de.from_cache,
    de.created_at
FROM download_events de
LEFT JOIN chat c ON c.chat_id = de.chat_id
WHERE de.user_id = $1
ORDER BY de.created_at DESC
LIMIT $2
`

type ListUserRecentDownloadEventsParams struct {
	UserID     int64
	LimitCount int32
}

type ListUserRecentDownloadEventsRow struct {
	ExtractorID   string
	ContentID     string
	ContentUrl    string
	ChatID        int64
	ChatType      ChatType
	ChatTitle     pgtype.Text
	ChatUsername  pgtype.Text
	ItemCount     int32
	TotalFileSize int64
	FromCache     bool
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListUserRecentDownloadEvents(ctx context.Context, arg ListUserRecentDownloadEventsParams) ([]ListUserRecentDownloadEventsRow, error) {
	rows, err := q.db.Query(ctx, listUserRecentDownloadEvents, arg.UserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRecentDownloadEventsRow
	for rows.Next() {
		var i ListUserRecentDownloadEventsRow
		if err := rows.Scan(
			&i.ExtractorID,
			&i.ContentID,
			&i.ContentUrl,
			&i.ChatID,
			&i.ChatType,
			&i.ChatTitle,
			&i.ChatUsername,
			&i.ItemCount,
			&i.TotalFileSize,
			&i.FromCache,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
