// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mutes.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveMutedChatsByType = `-- name: CountActiveMutedChatsByType :one
SELECT COUNT(*)::BIGINT
FROM muted_users m
JOIN chat c ON c.chat_id = m.user_id
WHERE c.type = $1
  AND m.expires_at > NOW()
`

func (q *Queries) CountActiveMutedChatsByType(ctx context.Context, type_ ChatType) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMutedChatsByType, type_)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveMutedUsers = `-- name: CountActiveMutedUsers :one
SELECT COUNT(*)::BIGINT
FROM muted_users
WHERE expires_at > NOW()
`

func (q *Queries) CountActiveMutedUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMutedUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getActiveMute = `-- name: GetActiveMute :one
SELECT user_id, reason, muted_by, expires_at, created_at
FROM muted_users
WHERE user_id = $1
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetActiveMute(ctx context.Context, userID int64) (MutedUsers, error) {
	row := q.db.QueryRow(ctx, getActiveMute, userID)
	var i MutedUsers
	err := row.Scan(
		&i.UserID,
		&i.Reason,
		&i.MutedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveMutedChatsByType = `-- name: ListActiveMutedChatsByType :many
SELECT
    m.user_id,
    m.reason,
    m.muted_by,
    m.expires_at,
    m.created_at,
    c.title,
    c.username,
    c.first_name,
    c.last_name
FROM muted_users m
JOIN chat c ON c.chat_id = m.user_id
WHERE c.type = $1
  AND m.expires_at > NOW()
ORDER BY m.expires_at ASC
LIMIT $2
`

type ListActiveMutedChatsByTypeParams struct {
	Type       ChatType
	LimitCount int32
}

type ListActiveMutedChatsByTypeRow struct {
	UserID    int64
	Reason    string
	MutedBy   int64
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Title     string
	Username  string
	FirstName string
	LastName  string
}

func (q *Queries) ListActiveMutedChatsByType(ctx context.Context, arg ListActiveMutedChatsByTypeParams) ([]ListActiveMutedChatsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listActiveMutedChatsByType, arg.Type, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMutedChatsByTypeRow
	for rows.Next() {
		var i ListActiveMutedChatsByTypeRow
		if err := rows.Scan(
			&i.UserID,
			&i.Reason,
			&i.MutedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Title,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveMutedUsers = `-- name: ListActiveMutedUsers :many
SELECT
    m.user_id,
    m.reason,
    m.muted_by,
    m.expires_at,
    m.created_at,
    c.username,
    c.first_name,
    c.last_name
FROM muted_users m
JOIN chat c ON c.chat_id = m.user_id AND c.type = 'private'
WHERE m.expires_at > NOW()
ORDER BY m.expires_at ASC
LIMIT $1
`

type ListActiveMutedUsersRow struct {
	UserID    int64
	Reason    string
	MutedBy   int64
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Username  string
	FirstName string
	LastName  string
}

func (q *Queries) ListActiveMutedUsers(ctx context.Context, limitCount int32) ([]ListActiveMutedUsersRow, error) {
	rows, err := q.db.Query(ctx, listActiveMutedUsers, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMutedUsersRow
	for rows.Next() {
		var i ListActiveMutedUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Reason,
			&i.MutedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const muteUser = `-- name: MuteUser :exec
INSERT INTO muted_users (user_id, reason, muted_by, expires_at, created_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    reason = EXCLUDED.reason,
    muted_by = EXCLUDED.muted_by,
    expires_at = EXCLUDED.expires_at,
    created_at = NOW()
`

type MuteUserParams struct {
	UserID    int64
	Reason    string
	MutedBy   int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) MuteUser(ctx context.Context, arg MuteUserParams) error {
	_, err := q.db.Exec(ctx, muteUser,
		arg.UserID,
		arg.Reason,
		arg.MutedBy,
		arg.ExpiresAt,
	)
	return err
}

const unmuteUser = `-- name: UnmuteUser :exec
DELETE FROM muted_users
WHERE user_id = $1
`

func (q *Queries) UnmuteUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, unmuteUser, userID)
	return err
}
