FROM golang:1.26-alpine3.22

RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    --mount=type=cache,target=/var/lib/apk,sharing=locked \
    apk add --no-cache \
        build-base=0.5-r3 \
        libheif-dev=1.19.8-r1 \
        ffmpeg=6.1.2-r2

WORKDIR /app

RUN --mount=type=cache,target=/go/pkg/mod \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.30.0 && \
    go install github.com/air-verse/air@v1.63.1

CMD ["air", "-c", ".air.toml"]
